### ISSUE TITLE
Doubled up scrobbling

### ISSUE THREAD

**Issue by SehWho** [Taiko2k/tauonmb#15]
When scrobbling is enabled and the player sends a completed play of a track, there will be a significant portion of the playtime where the currently playing track both has a completed scrobble and shows up as scrobbling now".

This causes problems in things that pull from recent plays, making it appear that the current track was both the last play and the current one.

![image](https://user-images.githubusercontent.com/18540948/47885834-00894900-de05-11e8-9135-cc46d1dde0dd.png)

**Comment by Taiko2k** [comment]
Ah yeah. A case of me being lazy. Because of as you say, Scrobbles *should* be submitted once the track has finished playing. (Although IIRC the Last.fm API documentation didn't explicitly stipulate this.)

I've gone ahead and fixed this. Might be a little while until I publish a new release since I did so recently.

**Comment by Taiko2k** [comment]
Fix for this is now live.
