### ISSUE TITLE
Support "add to the queue"

### ISSUE THREAD

**Issue by KiriKira** [Taiko2k/tauonmb#18]
Hope there is an option in the right-click menu that can add songs to the playing queue (in another word, play next / play after the current song). That will be wonderful!

**Comment by Taiko2k** [comment]
Actually this function does exist already. Tracks can be queued by wheel clicking them.

Though... this feature does seem to have poor accessibility. You're the 2nd person to ask me about it this week, so indeed it does seem like it should be added to the menu.

**Comment by KiriKira** [comment]
Thank you for reply! I tried wheel clicking and it works fine, great!
Yes, but still feeling the menu option will be more intuitive.
Love this project, thanks for your work!

**Comment by Taiko2k** [comment]
I had considered expanding the queue function. Though I wasn't sure how that should look like.

 - Could be as simple as just adding all the tracks of an album to the queue (Kind of ugly)
 - Add ability to add special flow diverter markers to the queue (I kind of like this idea, but would be very unintuitive from a user perspective)
 - Have a full UI component/overlay that shows queued tracks and albums with album art, allowing free re-aranging and deleting. (This is similar to what I've seen other players do)

But this brings me think about what the queue is for.

In my view, I see the Queue function as something to quickly divert the play flow. No so much for long enqueuing. 

For that you can simply make a new playlist, and drag and drop tracks/albums on to it. So in a way this is simpler and more flexible than a single force queue would be.

![output](https://user-images.githubusercontent.com/17271572/49481496-0d7bdb00-f890-11e8-8636-284e21c1685a.gif)

**Comment by legion1978** [comment]
you're right: it is to quickly disrupt the current play flow. sometimes you just want to listen to some album (not just a song) and i find myself painfully dragging it through the playlist. specially in a random albums playlist. 
it would be much easier just right-clicking the album name and select "enqueue this album" or "play album next".
now that would present some challenges, like what to do after that album is over. should it go back to the track was playing or continue from there on? should it follow the cursor, jump playlist, stop? so it would need options.
as for the queue itself (both tracks or albums) it would probably need some ui. a list of queued tracks, most likely. so they can be re-arranged. it would be hard to spot marked tracks in a long playlist.
for instance, i middle clicked several times a track to test. first time the N appeared to mark it, then a few dots, but i did not know how many times it was supposed to play, or i could not delete some of the instances, so i explored around and found the "clear queue" menu entry, but this erases all of it, not just the one i wanted (i pressume, since theres no feedback about it). and latest version shows neither N or dots...
thanks and i hope it helps :)

**Comment by Taiko2k** [comment]
I see what you're saying. Yes perhaps an interactive UI element possibly with an option like "Return to original position when finished" would be more useful over the current functionality.

And yes, currently, the queue can only be cleared entirely. Also to clarify the dots represent the repeat times. (but indeed, not their subsequent positions)
