### ISSUE TITLE
Decision on pruning or expanding view layouts?

### ISSUE THREAD

**Issue by Taiko2k** [Taiko2k/tauonmb#5]
Currently I feel the the "Gallery Only" view and the "Art + Tracks" view don't integrate well and are somewhat redundant. Should either of these be removed? (in order to make the UI/UX less confusing), left in place as is (To let the user decide if they are useful) or could they improved and if so how?

**Comment by legion1978** [comment]
hi there. im not sure im getting notifications on email ..ill check that out.

i would think theyd be somewhat redundant, but then again its useful to click on an album art and see them tracks in it (not sure about having them autoplay though), whereas album art only provide no extra info, yet some people are more visual and could prefer it this way, and maybe dont even need to know atm the track list, just play that album. maybe an option "autoplay on gallery view double click" (single click would only scroll the track list to that album) dunno if already exists.

i liked the visual approach to the layouts menu, though i think they should still have a title with the name on it, just for usability sake, like hovering mouse and see "gallery only" "art + tracks" "de/activate columns" etc. this also goes to the icons at the bottom of the player. basically what you have in the panel guide in the documentation.

cycling through the different layouts, i thought it may be one missing: track list with lyrics. for instance i commonly dont stay at the player desktop (so i cant see the album art in tauon) but i do jump to it to catch up with a line of a rare song, so for me it would make sense to keep open the track list, playing selected and the lyrics to the right as default. just an idea.

one thing i noticed, "paste lyrics" doesnt always work. how does this work? sometimes i try to paste chords (lyrics + chords) in it and nothing happens. may it be the html/text formatting if any? or does it show up after track change? (tried this too when pasting failed, no joy)

any way, great work!

**Comment by Taiko2k** [comment]
Yes, the gallery does have that function, its click to play, right click to jump track list. Perhaps I need to figure a better way to communicate that functionality, or at least document it, I think I might have missed that. ... Actually you're probably right, double click would be more consistent with what users typically expect, I might make it as an option, and/or make it the new default.

>some people are more visual and could prefer it this way, and maybe dont even need to know atm the track list, just play that album

That's kind of what I was thinking, but yeah, on the other hand I feel "gallery only" should have a pop out track selector of some sort. I implemented a test prototype, but I'm not satisfied with the design I came up with. Looked like this:

![screenshot from 2017-11-05 15-58-36](https://user-images.githubusercontent.com/17271572/32411551-a0dff974-c242-11e7-9c01-ae8aaac95903.png)

For the layout menu.. yeah, I considered adding labels to the icons. I probably should. Maybe an area of text below the icons that changes depending on which one the mouse is over. As for other buttons, I guess its 'tool tips' we're thinking of... As a design philosophy I really prefer to avoid timed interactions (like hold mouse button, or hover).

A tracks+lyrics view? I didn't think of that, yes that would be useful. I might add it as some sort of side bar option that replaces the album art with lyrics. (or maybe below the album art, though there's typically not much room there)

About the lyrics thing, I tested it and yeah you're right! There is an issue there, mainly the display doesn't update to the new lyrics if the track already had lyrics. Whoops.

**Comment by legion1978** [comment]
> That's kind of what I was thinking, but yeah, on the other hand I feel "gallery only" should have a pop out track selector of some sort.

there are a number of things a user might expect when right clicking on an album art: "reload/search album art" "add to queue" "play this album" and so on. i would suggest keep it simple, since i understand tauon is a player and not a music organizer. you may take a look at yarock player. it might give you some ideas.

> For the layout menu.. yeah, I considered adding labels to the icons.

the "problem" with that is that it would take up space, making the interface look cluttered. i think it would make tauon lose its slick style. thats what tooltips are for.. labels make more sense in mobile ui, because theres no hover. whereas tooltips keeps the user informed, while not getting in the way of the ui design. but its your call, you could test n see how it looks. consider diferent languages makes words longer/shorter so the space must be consistent, etc

> A tracks+lyrics view? 

yeah, basically what now is track list + album, lyrics replacing the album art or placed below it.

the lyrics query/paste should work if i cleared them first. that would make sense anyway. i clear the lyrics then query/paste a new one.. though i have the feeling it shows me the ones it had, after i re-query them.

is there a particular reason why pressing tab does not alternate through all of the available layout modes?
