### ISSUE TITLE
Screen saver not blanking (insomniac) (Linux Mint)

### ISSUE THREAD

**Issue by LightningStalker** [Taiko2k/tauonmb#8]
While Tauon is running the system never enters screen saver. Linux Mint 18.2 Sonya, Xenial 16.04

**Comment by Taiko2k** [comment]
I assume you're still on v2.6.2. This issue was fixed in a later version.

Unfortunately I'm not really prepared to support / build new packages for Mint right now. 

For a quick in-place patch you could run this command:

`sudo sed -i '/C-IS-----/a SDL_SetHint(SDL_HINT_VIDEO_ALLOW_SCREENSAVER, b"1")' /opt/tauon-music-box/tauon.py`

**Comment by LightningStalker** [comment]
Ok thanks I applied it and we'll know if it works by tomorrow.

**Comment by LightningStalker** [comment]
It's fixed, thanks.
